### ISSUE TITLE
"Default 'dataset_inout' method not defined for generic datasets"

### ISSUE THREAD

**Issue by ger-e** [AstraZeneca-NGS/LogMl#2]
`ERROR Datasets.default_in_out (datasets.py:97): Default 'dataset_inout' method not defined for generic datasets`

is this a bug or functionality that's yet to be coded?

**Comment by pcingola** [comment]
Functionality. There is no way for the program to know an arbitrary dataset. We might add restrictions on how we define those objects in the future to allow natural partitions.
